apiVersion: v1
kind: Service
metadata:
     name: flask-app
spec:
    selector:
        name: flask-app
    type: LoadBalancer
    externalIPs: 
    - 192.168.1.11
   ports:
       - protocol: TCP
         port: 80
         targetPort: 5000
