apiVersion: v1
kind: Service
metadata:
     name: flask-app
spec:
    selector:
        name: flask-app
   
   ports:
       - protocol: TCP
         port: 80
         targetPort: 5000
   type: LoadBalancer
status:
  LoadBalancer:
    ingress:
    - ip: 192.0.2.127
    - externalIPs: 172.168.0.1
